"""upgrade contacts table

Revision ID: e59f14f9e6c6
Revises: 16956b006cff
Create Date: 2026-09-23 13:00:00.740842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e59f14f9e6c6'
down_revision: Union[str, Sequence[str], None] = '16956b006cff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('notes', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'notes')
    # ### end Alembic commands ###
