
name: Test Self-Hosted Runner

"on":
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-runner:
    name: Test on Kali Linux
    runs-on: self-hosted

    steps:
      - name: Identify runner machine
        run: |
          echo "Hello from my self-hosted runner!"
          echo "Username:"
          whoami
          echo "Hostname:"
          hostname
          echo "Operating system:"
          uname -a
          echo "Docker version:"
          docker --version